import type {AllSystemInfo} from "../types/system-info";

export function exportAsMarkdown(data: AllSystemInfo): string {
    const lines: string[] = [];
    const computerName = data.computer?.name ?? "System Report";
    const now = new Date().toLocaleString();

    lines.push(`# ${computerName}`);
    lines.push(`> Generated by CIRG on ${now}`);
    lines.push("");

    const mdTable = (headers: string[], rows: string[][]) => {
        const hdr = `| ${headers.join(" | ")} |`;
        const sep = `| ${headers.map(() => "---").join(" | ")} |`;
        const body = rows.map(r => `| ${r.join(" | ")} |`).join("\n");
        return `${hdr}\n${sep}\n${body}`;
    };

    if (data.computer) {
        const c = data.computer;
        lines.push("## Computer");
        lines.push("");
        lines.push(mdTable(
            ["Property", "Value"],
            [
                ["Name", c.name],
                ["Domain", c.domain],
                ["Manufacturer", c.manufacturer],
                ["System Type", c.system_type],
                ["OS", `${c.operating_system.name} ${c.operating_system.version}`],
                ["Architecture", c.operating_system.architecture],
                ["Timezone", c.operating_system.timezone],
                ["BIOS", `${c.bios.manufacturer} ${c.bios.version}`],
            ]
        ));
        lines.push("");
    }

    if (data.cpu) {
        const c = data.cpu;
        lines.push("## CPU");
        lines.push("");
        lines.push(mdTable(
            ["Property", "Value"],
            [
                ["Name", c.name],
                ["Cores", String(c.cores)],
                ["Logical Processors", String(c.logical_processors)],
                ["Max Clock (MHz)", String(c.max_clock_mhz)],
                ["Socket", c.socket],
                ["Architecture", c.architecture],
                ["L2 Cache (KB)", String(c.l2_cache_kb)],
                ["L3 Cache (KB)", String(c.l3_cache_kb)],
            ]
        ));
        lines.push("");
    }

    if (data.gpu && data.gpu.adapters.length > 0) {
        lines.push("## GPU");
        lines.push("");
        for (const a of data.gpu.adapters) {
            lines.push(`### ${a.name}`);
            lines.push("");
            lines.push(mdTable(
                ["Property", "Value"],
                [
                    ["Driver Version", a.driver_version],
                    ["VRAM (MB)", String(a.adapter_ram_mb)],
                    ["Resolution", a.resolution],
                    ["Refresh Rate", `${a.refresh_rate} Hz`],
                    ["Status", a.status],
                ]
            ));
            lines.push("");
        }
    }

    if (data.memory && data.memory.slots.length > 0) {
        lines.push("## Memory");
        lines.push("");
        lines.push(mdTable(
            ["Bank", "Capacity (GB)", "Speed (MHz)", "Type", "Manufacturer", "Part Number"],
            data.memory.slots.map(s => [s.bank_label, String(s.capacity_gb), String(s.speed_mhz), s.memory_type, s.manufacturer, s.part_number])
        ));
        lines.push("");
    }

    if (data.disk) {
        lines.push("## Storage");
        lines.push("");
        if (data.disk.physical_disks.length > 0) {
            lines.push("### Physical Disks");
            lines.push("");
            lines.push(mdTable(
                ["Model", "Interface", "Media Type", "Size (GB)", "Status"],
                data.disk.physical_disks.map(d => [d.model, d.interface_type, d.media_type, d.size_gb.toFixed(1), d.status])
            ));
            lines.push("");
        }
        if (data.disk.logical_disks.length > 0) {
            lines.push("### Logical Drives");
            lines.push("");
            lines.push(mdTable(
                ["Drive", "File System", "Total (GB)", "Free (GB)", "Used (GB)", "Usage %"],
                data.disk.logical_disks.map(d => [d.device_id, d.file_system, d.total_gb.toFixed(1), d.free_gb.toFixed(1), d.used_gb.toFixed(1), d.usage_pct.toFixed(1)])
            ));
            lines.push("");
        }
    }

    if (data.network && data.network.adapters.length > 0) {
        lines.push("## Network");
        lines.push("");
        for (const a of data.network.adapters) {
            lines.push(`### ${a.name}`);
            lines.push("");
            lines.push(mdTable(
                ["Property", "Value"],
                [
                    ["MAC Address", a.mac_address],
                    ["Speed", a.speed],
                    ["Gateway", a.gateway],
                    ["DHCP", String(a.dhcp_enabled)],
                    ["IPv4", a.ipv4_addresses.join(", ")],
                    ["IPv6", a.ipv6_addresses.join(", ")],
                    ["DNS", a.dns_servers.join(", ")],
                ]
            ));
            lines.push("");
        }
    }

    if (data.security) {
        const s = data.security;
        lines.push("## Security");
        lines.push("");
        lines.push(mdTable(
            ["Property", "Value"],
            [
                ["Secure Boot", String(s.secure_boot)],
                ["UAC", String(s.uac)],
                ["BitLocker", String(s.bit_locker)],
                ["RDP Enabled", String(s.rdp_enabled)],
                ["Antivirus", s.antivirus ?? "Not detected"],
                ["Pending Updates", s.pending_updates],
            ]
        ));
        lines.push("");
    }

    if (data.software && data.software.programs.length > 0) {
        lines.push("## Installed Software");
        lines.push("");
        lines.push(mdTable(
            ["Name", "Version", "Publisher", "Install Date"],
            data.software.programs.map(p => [p.name, p.version, p.publisher, p.install_date])
        ));
        lines.push("");
    }

    return lines.join("\n");
}
